### ISSUE TITLE
Implement rebuttals

### ISSUE THREAD

**Issue by db0** [Fediseer/FediseerGUI#162] opened 2023-11-03 10:03 UTC
Fediseer allows admins of censures/hesitates instances to issue a rebuttals to their own defense.

![image](https://github.com/Fediseer/FediseerGUI/assets/296513/8d98e047-9661-4f52-868f-75677b9708e2)

**Comment by RikudouSage** [comment] 2023-11-05 17:09
Duplicate of #155

**Closed by RikudouSage** 2023-11-05 17:09 UTC
